### ISSUE TITLE
Multiple server processes

### ISSUE THREAD

**Issue by afonsosantos** [hortio/docker-blynk#1]
Hi,

I'm writing to ask if this behaviour is normal or not: whenever I run `docker-compose up -d`, new processes of this kind are created, and the old ones are not deleted:

![image](https://user-images.githubusercontent.com/46262740/87889450-99bd2080-ca29-11ea-94a2-c85f04652f24.png)

Also, is there a way to preserve the Let's Encrypt certificates? I'm running out of quota easily, because every `docker-compose up -d` generates a new certificate.

Thank you!

**Comment by kumekay** [comment]
Hi @afonsosantos ,

As for the first part, these are just different threads of the same process
that share the same virtual memory. It's ok.

As for certificates,
if I understand correctly,  blynk just downloads certificate directly to
the work directory (which is `/blynk` in the container)
https://github.com/blynkkk/blynk-server/blob/master/server/acme/src/main/java/cc/blynk/server/acme/AcmeClient.java#L33-L39

Unfortunately, I cannot come up with a way to mount a file that doesn't
exist on the host inside the container. If we create empty files on the
host and mount them, cert generation will be broken.

**Comment by afonsosantos** [comment]
Hi @kumekay ,

Thank you for the response.

> As for the first part, these are just different threads of the same process
that share the same virtual memory. It's ok.

Thank you for the explanation, made it much clearer.

> Unfortunately, I cannot come up with a way to mount a file that doesn't
exist on the host inside the container. If we create empty files on the
host and mount them, cert generation will be broken.

That makes sense. Part of the problem was that I was testing and the Let's Encrypt quota went out, but it't up and running again.

Thanks again!
