### ISSUE TITLE
Docker hortio/blynk:v0.41.15 - unable to connect via ws

### ISSUE THREAD

**Issue by VanillaFord** [hortio/docker-blynk#3]
...see also: https://github.com/blynkkk/blynk-server/issues/1390
I initially raised the issue in the blynk-server repository, but think rather is related to the image itself, not the bylnck/server package/repo.

After pulling latest docker image (docker pull hortio/blynk:v0.41.15) clients are unable to connect via plain/non-TLS WebService connections.
Clients run into timeout.
Rollback to v0.41.14 (docker pull hortio/blynk:v0.41.14) immediately solves this issue.

**Comment by VanillaFord** [comment]
...looks like the API call has changed to "ws://IP-of-docker-container:8080/websocket" ... see: https://github.com/blynkkk/blynk-server/issues/1390#issuecomment-779877425
Aparently an issue with the blynk-server implementation, as normally both URLs sould work. See Issue in blynk-server repo above.

**Comment by VanillaFord** [comment]
....see comment above and https://github.com/blynkkk/blynk-server/issues/1390#issuecomment-779897490

**Comment by kumekay** [comment]
Thank you for letting me know, I'll update the image as soon as the next version will be released

**Comment by MasterCATZ** [comment]
is this also why now when trying to access my local server it is now being re-directed to the www server ? https://blynk.cc then   https://blynk.io ?
