### ISSUE TITLE
Update to server-0.41.17 to patch Log4j2 vulnerability

### ISSUE THREAD

**Issue by codmandev** [hortio/docker-blynk#4]
Blynk updated to .17 to patch the Log4j2 vulnerability. Can you possibly patch the docker container? I'm unsure of how to do it myself and I don't want to break it.

**Comment by kumekay** [comment]
@codmandev  thank you for the issue, I missed that release, it's published now

**Comment by codmandev** [comment]
@kumekay Thank you for the update. Much appreciated.
